print("My name is Adrian Garcia.")
print("Today is my first day in this course")
print("The weather is gloomy")
print("Today is January 4th, 2021")
print("The gyms will be packed today")
print("SPY took a dip today")
print("This is the first Monday of the year")
print("AI is cool")
print("The monetization of data.")